/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gd_JNI */

#ifndef _Included_com_gd_JNI
#define _Included_com_gd_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gd_JNI
 * Method:    getPassphrase
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gd_JNI_getPassphrase
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
